# \u7AEF\u53E3\u53F7
server:
  port: 8761
# \u914D\u7F6E\u5E94\u7528\u7A0B\u5E8F\u540D\u79F0
spring:
  application:
    name: cloud-eureka
# \u914D\u7F6E\u6CE8\u518C\u670D\u52A1\u4E2D\u5FC3
eureka:
  instance:
    hostname: localhost
  client:
    # \u8868\u660E\u81EA\u5DF1\u4E0D\u662F\u4E00\u4E2A\u5BA2\u6237\u7AEF\uFF0C\u5E76\u4E14\u4E0D\u8FDB\u884C\u81EA\u6CE8\u518C
    register-with-eureka: false
    fetch-registry: false
    # \u6CE8\u518C\u4E2D\u5FC3\u7684\u8BBF\u95EE\u5730\u5740
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
